Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.box_download_insecure = true
    config.vm.hostname = "db"
    config.vm.network "private_network", ip: "172.168.10.12"
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "600"
    end
    config.vm.provision "shell", path: "db.sh"
end